### ISSUE TITLE
コーディングスタイルを決める

### ISSUE THREAD

**Issue by tubo28** [comp-prog-jp-library-standard/competitive-programming-library#1]

**Comment by tubo28** [comment]
clang-format の config を決めてしまえば良さそう
例 (好みが分かれそうですが) ↓

```
IndentWidth: 4
ColumnLimit: 100
AccessModifierOffset: -4
AlwaysBreakTemplateDeclarations: true
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: true
AllowShortLoopsOnASingleLine: true
```

適用して diff があるとテストで落とすなどすればいいと思います

**Comment by tubo28** [comment]
📝 Can clang-format tell me if formatting changes are necessary? https://stackoverflow.com/a/22866610

**Comment by asi1024** [comment]
BasedOnStyle 決めるだけでもいいんじゃないかなとも思う

**Comment by koba-e964** [comment]
Contributor の中では `IndentWidth: 2` 派が多いように見える (asi1024, beet, koba-e964, vvataarne) ので indentwidth は2がよさそうに見えます。
特に理由がなければ BaseOnStyle: LLVM でいいとおもいます。 (https://clang.llvm.org/docs/ClangFormatStyleOptions.html で最初に出てくるため)
