### ISSUE TITLE
ライブラリの依存関係

### ISSUE THREAD

**Issue by asi1024** [comp-prog-jp-library-standard/competitive-programming-library#13]
競技プログラミングでは普通は1ファイル提出の制約があるため，
ライブラリ同士の依存関係を特別な方法で表現する必要がある．

**Comment by asi1024** [comment]
例えば，コメントで `@depends on [相対パス]` のように書くようにして，
自動テストやリファレンスではこれをうまく展開するようにする，とか

**Comment by koba-e964** [comment]
LGTM です。

**Comment by asi1024** [comment]
include 部分は bits 的なのを自前で用意して複数回 include されることを防ぐようすることにします
(C++ だと複数回 include しても大丈夫ですが，他の言語だとそうもいかないので)
