### ISSUE TITLE
セグメント木を追加

### ISSUE THREAD

**Issue by vvataarne** [comp-prog-jp-library-standard/competitive-programming-library#17]
一点更新・区間演算ができるセグメント木を追加する

決めること:

* 名前 `SegTree` or `SegmentTree` (他にありますか)
* 抽象化をどうやって実現するか
* 半開区間 or 閉区間 or 開区間
* 0-indexed or 1-indexed (配列で実装する場合)
* 再帰 or 非再帰

**Comment by asi1024** [comment]
内部設計と外部設計で切り分けて議論したいです．

**Comment by beet-aizu** [comment]
indexingと再帰／非再帰が内部設計で他は外部設計ですかね。
名前については一点更新区間取得、区間更新一点取得、区間更新区間取得で区別できるようにしないと混乱を招きそうです。
抽象化についてはそれぞれメリット／デメリットがあるのでいくつかパターンを用意する（構造体を渡す、ラムダを渡す）必要があると思います。
区間表現はSTLに合わせるという面で半開区間を推したいです。

**Comment by asi1024** [comment]
何種類も表現方法を用意するのはメンテナンスコストを上げるのであまり望ましくないかと．
少なくともそれぞれのメリット，デメリットを具体的に列挙してから議論するべきだと思います．

**Comment by asi1024** [comment]
とりあえず実際のコードがあったほうが議論しやすいかもしれないので，雑にPRを作っちゃってそれをたたき台にしてもよいかもしれません．

**Comment by koba-e964** [comment]
とりあえずやります
