### ISSUE TITLE
推奨コンパイラを決める

### ISSUE THREAD

**Issue by beet-aizu** [comp-prog-jp-library-standard/competitive-programming-library#3]
gccに限定するか？（__builtin系とかbitsとか使いたい気もします）バージョンをどうするか

**Comment by asi1024** [comment]
少なくとも貼り付けライブラリで bits/stdc++ を使うメリットはなさそうです

**Comment by asi1024** [comment]
AtCoder のバージョンに合わせる感じでいいんじゃないかと思います
- GCC 5.4.1
- Clang 3.8.0

**Comment by beet-aizu** [comment]
確かにpopcount等は自前のものを用意してそれを一緒に貼り付るようにすれば良さそうですね。
特に断りがない場合はGCCでもClangでも動くようにするべきだと思います（MacのデフォルトコンパイラがClangなので）

**Comment by asi1024** [comment]
このissueも解決している？
