### ISSUE TITLE
C++14に対応する

### ISSUE THREAD

**Issue by beet-aizu** [comp-prog-jp-library-standard/competitive-programming-library#33]
AtCoderを基準にするのであればコンパイルオプションはC++14であるべきではないでしょうか

**Comment by beet-aizu** [comment]
boostにも対応する必要がありそうです
https://agc028.contest.atcoder.jp/rules

**Comment by asi1024** [comment]
boost 対応はしなくてもよいと思います．他のコンテストサイトで使いづらくなるので

**Comment by beet-aizu** [comment]
それもそうですね　使いたい人が出てきたらまた別のissueで議論しましょう
