### ISSUE TITLE
CI 時にコードを実行するテストを行う

### ISSUE THREAD

**Issue by asi1024** [comp-prog-jp-library-standard/competitive-programming-library#9]
方針は大別して以下の2つです
- 既存のオンラインジャッジを利用する
- 自前でテストを用意する

**Comment by asi1024** [comment]
オンラインジャッジを利用するのは楽ですし，作業量が少ない分 PR も受けやすいと思います．

基本的には何らかのオンラインジャッジを利用するようにして，存在しないものについては自前でテストを書く，というのが良いのかなと思っています．

**Comment by asi1024** [comment]
オンラインジャッジのテストケースを引っ張ってくるだけ，というのはどうでしょうか．

**Comment by koba-e964** [comment]
それなら良さそうです
